let stationP = {
	stations: [{
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.29,
		stationStstus: 50,
		lon: 123.123,
		lat: 124.124,
		distance: 12,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 123.123,
			stationLat: 124.124,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 12,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}, {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.32,
		stationStstus: 50,
		lon: 183.123,
		lat: 166.124,
		distance: 12,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 183.123,
			stationLat: 166.124,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 22,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}, {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.25,
		stationStstus: 50,
		lon: 155.123,
		lat: 104.124,
		distance: 19,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 155.123,
			stationLat: 104.124,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 19,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}, {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.21,
		stationStstus: 50,
		lon: 223.123,
		lat: 224.124,
		distance: 17,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 223.123,
			stationLat: 224.124,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 17,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}, {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.33,
		stationStstus: 50,
		lon: 123.173,
		lat: 114.134,
		distance: 16,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 123.173,
			stationLat: 114.134,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 16,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}, {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.29,
		stationStstus: 50,
		lon: 153.123,
		lat: 154.124,
		distance: 70,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 153.123,
			stationLat: 154.124,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 70,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}, {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.39,
		stationStstus: 50,
		lon: 143.123,
		lat: 120.124,
		distance: 17,
		info: {
			id: 1111112222,
			stationId: "充电站ID",
			stationName: "充电站名称",
			countryCode: "CN",
			areaCode: "充电站省市辖区编码",
			address: "详细地址详细地址详细地址",
			stationTel: "17711177777",
			serviceTel: "16611661166",
			stationtype: 50,
			stationStatus: 50,
			parkNum: 30,
			stationLng: 123.123,
			stationLat: 124.124,
			siteGuide: "站点引导",
			construction: 1,
			pictures: "站点照片JSON串",
			matchChars: "使用车型描述",
			parkInfo: "车位楼层及数量描述",
			busineHours: "营业时间描述",
			electricityFee: "充电电费描述",
			serviceFee: "服务费描述",
			parkFee: "停车费描述",
			payment: "支付方式::刷卡、线上、现金。其中电子钱包类卡为刷卡，身份鉴权卡、微信/支付宝、APP为线上",
			supportOrder: 1,
			platType: 1,
			remark: "备注信息",
			delFlag: 0,
			createTime: Date(),
			updateTime: Date(),
			equipmentCount: 60,
			connectorCount: 80,
			operatorName: "运营商名称"
		},
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		imgs: ["", ""],
		userDistance: 12,
		tagList: [{
				name: "12"
			},
			{
				name: "34"
			}
		],
		nearest: false,
	}],
	stationInfo: {
		id: 1111111111111111,
		stationId: "站点ID",
		stationName: "站点名称",
		currentPrice: 0.29,
		stationStstus: 50,
		address: "详细地址详细地址详细地址",
		lon: 123.123,
		lat: 124.124,
		imgs: ["", ""],
		totalFastGun: 20,
		freeFastGun: 10,
		totalGun: 30,
		freeGun: 5,
		pileList: [{
			id:123456789,
			equipmentId:"123456789",
			name:"桩名",
			equipmentType:1,
			gunList:[{
				id:1122334455,
				connectorId:"1122334455",
				connectorName:"充电接口名",
				status:1,
				connectorType:1,
				parkStatus:10,
				power:10,
				chargingPer:0.8,
				remainMinute:8,
				startTm:Date()
			},{
				id:2233445566,
				connectorId:"2233445566",
				connectorName:"充电接口名",
				status:1,
				connectorType:1,
				parkStatus:10,
				power:10,
				chargingPer:0.8,
				remainMinute:8,
				startTm:Date()
			}]
		},{
			id:234567890,
			equipmentId:"234567890",
			name:"桩名",
			equipmentType:1,
			gunList:[{
				id:1122334455,
				connectorId:"1122334455",
				connectorName:"充电接口名",
				status:1,
				connectorType:1,
				parkStatus:10,
				power:10,
				chargingPer:0.8,
				remainMinute:8,
				startTm:Date()
			},{
				id:2233445566,
				connectorId:"2233445566",
				connectorName:"充电接口名",
				status:1,
				connectorType:1,
				parkStatus:10,
				power:10,
				chargingPer:0.8,
				remainMinute:8,
				startTm:Date()
			}]
		}],
		priceList: [],
		attactInfo: "运维信息",
		stationPhone: "17711177777",
		servicePhone: "16611661166",
		platType: 1,
		busineHours: "营业时间描述"
	},
	cities: [{
			label: "广州市",
			value: {
				latitude: 39.905023,
				longitude: 116.384502
			},
		}, {
			label: "上海市",
			value: {
				latitude: 31.230525,
				longitude: 121.473667
			},
		},
		{
			label: "北京市",
			value: {
				latitude: 39.905023,
				longitude: 116.384502
			},
		},
	],
	selectedCity: {
		city: "广东",
		nation: "中国"
	},
	mapStartLocation: {
		lat: 113.12323,
		lon: 21.51742,
	},
	mapCenterLocation: {
		lat: 113.909,
		lon: 21.742,
	},
	swiperlist: [{
			image: '/static/virtual/swiper1.jpg',
			title: 'one'
		},
		{
			image: '/static/virtual/swiper2.jpg',
			title: 'two'
		},
		{
			image: '/static/virtual/swiper3.jpg',
			title: 'three'
		}
	],
	funcList: [{
		text: "充电",
		iconPath: "/static/mine/charge.png",
		pagePath: ""
	}, {
		text: "充电",
		iconPath: "/static/mine/charge.png",
		pagePath: ""
	}, {
		text: "爱车",
		iconPath: "/static/mine/car.png",
		pagePath: ""
	}, {
		text: "订单",
		iconPath: "/static/mine/order.png",
		pagePath: ""
	}]
}

let myP = {
	userInfo: {
		uid: 11111,
		phobeCode: '',
		mobile: '18819192828',
		nickName: 'hhh',
		wechatName: 'hehehe',
		unionIdWx: '',
		openIdWx: '',
		sex: 1,
		country: '',
		province: '',
		city: '',
		birthday: '',
		avatarUrl: '/static/missing-face-1.jpg',
		platform: '',
		disableFlag: '',
		registerTime: '',
		lastVisiTime: '',
		lastVisitIp: '',
		lastVisitArea: '',
		orgFlag: '',
		remark: '',
		deFlag: '',
		createTime: '',
		updateTime: ''
	},
	token: "QQYjtAxrZh2MIocSkjXEipSqMfvQa4bM",
};

export {
	stationP,
	myP
}